### ISSUE TITLE
可以添加评论及访问统计功能？谢谢

### ISSUE THREAD

**Issue by kklod** [zoeingwingkei/frame#10]

**Comment by zuTao01** [comment]
请问你知道为什么 图片gallery也显示在博客blog里面？

**Comment by zoeingwingkei** [comment]
评论功能会添加在下一个版本中。访问功能也在研究中了。
因为作者的主业其实是设计师，代码水平非常业余，所以开发周期会比较慢，抱歉～

**Comment by zoeingwingkei** [comment]
> 请问你知道为什么 图片gallery也显示在博客blog里面？

首页的blog链接是跳转到archive的，archive包含所有的文章。

**Comment by kklod** [comment]
> 评论功能会添加在下一个版本中。访问功能也在研究中了。
> 因为作者的主业其实是设计师，代码水平非常业余，所以开发周期会比较慢，抱歉～

👍👍👍
