### ISSUE TITLE
请问一下可以设置文章隐藏吗

### ISSUE THREAD

**Issue by lingyunfx** [zoeingwingkei/frame#11]
想请教下在文章开头设置了 hide: true 可以实现文章隐藏吗？我试过了好像没有生效

---
title: 我是一篇文章
date: 2021-08-16 08:00:00
hide: true
---

**Comment by zoeingwingkei** [comment]
> 想请教下在文章开头设置了 hide: true 可以实现文章隐藏吗？我试过了好像没有生效
> 
> ## title: 我是一篇文章
> date: 2021-08-16 08:00:00
> hide: true

目前的主题还没有支持这个功能～ 下一个版本会考虑加上的～

**Comment by lingyunfx** [comment]
谢谢回复 很喜欢这个主题。 暂时我可以用page代替一下 有些文章不想直接显示在archives里

**Comment by zoeingwingkei** [comment]
> 谢谢回复 很喜欢这个主题。 暂时我可以用page代替一下 有些文章不想直接显示在archives里

你好～我在尝试实现这个隐藏功能的时候发现 hexo 本身有一个插件可以完美解决这个问题。
链接在此：https://github.com/prinsss/hexo-hide-posts/blob/master/README_ZH.md
这个插件安装和使用都非常方便，所以我就没有必要在自己的主题里实现了。

**Comment by lingyunfx** [comment]
非常感谢！
