### ISSUE TITLE
你好请问 Gallery 上的 featured image 路径应该如何配置呢

### ISSUE THREAD

**Issue by NulllStack** [zoeingwingkei/frame#16]

**Comment by NulllStack** [comment]
我把 package.json 下的 hexo-asset-image 和 hexo-asset-link 插件去除了，用了 hexo-image-link 。 不知道会不会有什么影响

**Comment by NulllStack** [comment]
我把想要显示在 Gallery 上的图片放在了 post assets folder 里面了

**Comment by zoeingwingkei** [comment]
> 我把想要显示在 Gallery 上的图片放在了 post assets folder 里面了

你好，我认为较妥当的路径配置就是用绝对路径。

举个例子，你的文章路径为`/2022/01/01/sample`，对应的 asset folder 的路径为`/2022/01/01/sample/`，你的图片路径则为`feature: /2022/01/01/sample/image.jpg`

**Comment by NulllStack** [comment]
我本来是尝试这样做了，但是图片不显示，我现在是把图片放在了主题根目录下的 source 里面就正常显示了，但是这样有点怪怪的..

**Comment by NulllStack** [comment]
是因为 front matter 的 `featured_image` 和 `feature` 有区别吗

**Comment by zoeingwingkei** [comment]
> 是因为 front matter 的 `featured_image` 和 `feature` 有区别吗

呀抱歉，应该是`featured_image: /2022/01/01/sample/image.jpg`
asset folder 在项目文件里的路径应该是 `source/_posts/sample` , 所以相应的图片路径应该是 `source/_posts/sample/image.jpg`？

**Comment by NulllStack** [comment]
是的😂 我本来是按你的例子这么做但是图片不论是本地还是deploy之后都会找不到图片资源，我现在是放在了 'theme/frame/gallery_images/' 这样子的话我是通过 ' featured_image: gallery_inages/myImage.jpg'，虽然这样问题解决了但是资源的管理就挺麻烦的🤔

**Comment by zoeingwingkei** [comment]
> 是的😂 我本来是按你的例子这么做但是图片不论是本地还是deploy之后都会找不到图片资源，我现在是放在了 `theme/frame/gallery_images/` 这样子的话我是通过 `featured_image: /gallery_images/myImage.jpg`，虽然这样问题解决了（虽然不理解为什么）但是资源的管理就挺麻烦的🤔

解决了就好嘿嘿 我一般都是把图片放在云端，所以没有遇到过这种问题😂
