### ISSUE TITLE
搜索功能无效

### ISSUE THREAD

**Issue by zzwu29** [zoeingwingkei/frame#40]
您好！非常欣赏您的主题。
但是他在我的环境中出现了一些问题，在我按照您的博客配置后，点击search，会跳转到当前地址+#的地址，并无搜索框出现。
请问有对应的处理方法吗？

**Comment by zoeingwingkei** [comment]
> 您好！非常欣赏您的主题。 但是他在我的环境中出现了一些问题，在我按照您的博客配置后，点击search，会跳转到当前地址+#的地址，并无搜索框出现。 请问有对应的处理方法吗？

你好，感谢你的支持～搜索功能需要先安装插件 [hexo-generator-searchdb](https://github.com/theme-next/hexo-generator-searchdb)。详细的用法介绍请参考[这篇文章](https://frame.zhangyongqi.com/2022/08/05/local-search/)。

**Comment by zzwu29** [comment]
您好，我已经按照文章中的所有步骤执行，但仍无法使用搜索功能，请问目前您的机器上仍然能够成功执行搜索功能吗？
